site_name: Python Investment Portfolio Optimization with Hyper-parameters (Pipoh)

theme:
  name: readthedocs
  analytics: G-G9NK6H51HJ

nav:
  - Inicio: 'index.md'
  - Mean-variance Formulation: 'mv_formulation.md'
  - Evaluation metrics: 'performance_evaluation_metrics.md'
