site_name: Pipoh

theme:
  name: readthedocs
  analytics: G-G9NK6H51HJ

nav:
  - Introduction: 'index.md'
  - Tutorials: '02_tutorials/index_tutorials.md'
  - Mean-variance Strategies: '03_mv_formulation_files/index_mv_formulation.md'
  - Optimizers: '04_Optimizers/index_hyper_parameters.md'
  - Performance evaluation metrics: '05_performance_evaluation_metrics/index_performance_evaluation_metrics.md'
  - Other information: '06_other_information/index_other_information.md'
